//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturaCajaDetRubros
    {
        public int IDApertura { get; set; }
        public int IDRubro { get; set; }
        public int Cantidad { get; set; }
        public decimal Valor { get; set; }
        public string Tipo { get; set; }
    
        public virtual AperturaCaja AperturaCaja { get; set; }
        public virtual DesgloceRubro DesgloceRubro { get; set; }
    }
}
