//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturaCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AperturaCaja()
        {
            this.AperturaCajaDet = new HashSet<AperturaCajaDet>();
            this.AperturaCajaDetRubros = new HashSet<AperturaCajaDetRubros>();
            this.CierreCaja = new HashSet<CierreCaja>();
            this.DetalleApertura = new HashSet<DetalleApertura>();
        }
    
        public int ID { get; set; }
        public int IDPtoVenta { get; set; }
        public int IDUsuario { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public decimal MontoAperturaEfectivo { get; set; }
        public decimal MontoAperturaOtros { get; set; }
        public Nullable<decimal> MontoCierreEfectivo { get; set; }
        public Nullable<decimal> MontoCierreOtros { get; set; }
        public string ObservacionesApertura { get; set; }
        public string ObservacionesCierre { get; set; }
        public string Estado { get; set; }
    
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AperturaCajaDet> AperturaCajaDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AperturaCajaDetRubros> AperturaCajaDetRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreCaja> CierreCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleApertura> DetalleApertura { get; set; }
    }
}
