//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        public int ID { get; set; }
        public int IDAS { get; set; }
        public int IDCT { get; set; }
        public int IDPCO { get; set; }
        public int IDPCU { get; set; }
        public string Naturaleza { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual CamposTransaccion CamposTransaccion { get; set; }
    }
}
