//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBODetalle
    {
        public int ID { get; set; }
        public int IDCOMBO { get; set; }
        public int IDPRODUCTO { get; set; }
        public string TipoProd { get; set; }
        public string PromocionProd { get; set; }
        public Nullable<decimal> DescuentoNuevo { get; set; }
        public decimal Descuento { get; set; }
        public decimal CantidadProd { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public decimal TotalCombo { get; set; }
    }
}
