//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreCaja
    {
        public int IDApertura { get; set; }
        public short Linea { get; set; }
        public string Rubro { get; set; }
        public decimal Monto { get; set; }
    
        public virtual AperturaCaja AperturaCaja { get; set; }
    }
}
