//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.ClienteEmail = new HashSet<ClienteEmail>();
            this.ClienteInfoAdicional = new HashSet<ClienteInfoAdicional>();
            this.DevVenta = new HashSet<DevVenta>();
            this.FactVenta = new HashSet<FactVenta>();
            this.ProformaVta = new HashSet<ProformaVta>();
            this.Tarjeta = new HashSet<Tarjeta>();
        }
    
        public int IDCT { get; set; }
        public Nullable<int> IDCG { get; set; }
        public Nullable<int> IDCiudad { get; set; }
        public Nullable<int> IDTipoIdentificacion { get; set; }
        public string CEDRUC { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public Nullable<bool> SujetoRetencion { get; set; }
        public string TipoContribuyente { get; set; }
        public string TipoEntidad { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual CategoriaCliente CategoriaCliente { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteEmail> ClienteEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteInfoAdicional> ClienteInfoAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevVenta> DevVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactVenta> FactVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaVta> ProformaVta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta { get; set; }
    }
}
