//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboImagen
    {
        public int ID { get; set; }
        public int IDCB { get; set; }
        public System.Guid IDGUID { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
