//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetDispensadorIslero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetDispensadorIslero()
        {
            this.DetalleApertura = new HashSet<DetalleApertura>();
        }
    
        public int IDDDI { get; set; }
        public int IDISL { get; set; }
        public int IDDISP { get; set; }
        public int IDPD { get; set; }
        public string Estado { get; set; }
    
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleApertura> DetalleApertura { get; set; }
        public virtual Dispensador Dispensador { get; set; }
        public virtual Islero Islero { get; set; }
    }
}
