//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevCompra()
        {
            this.DCDetalle = new HashSet<DCDetalle>();
        }
    
        public int IDDC { get; set; }
        public int IDSU { get; set; }
        public int IDPV { get; set; }
        public int IDFC { get; set; }
        public int IDUS { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Autorizacion { get; set; }
        public string Numero { get; set; }
        public decimal SubtotalIVA { get; set; }
        public decimal SubtotalIVA0 { get; set; }
        public decimal Subtotal { get; set; }
        public decimal PorcentajeDesc { get; set; }
        public decimal Descuento { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCDetalle> DCDetalle { get; set; }
        public virtual FactCompra FactCompra { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
