//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevVenta()
        {
            this.DVDetalle = new HashSet<DVDetalle>();
        }
    
        public int IDDV { get; set; }
        public int IDSU { get; set; }
        public int IDPT { get; set; }
        public int IDCT { get; set; }
        public int IDFV { get; set; }
        public int IDUS { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Autorizacion { get; set; }
        public string Numero { get; set; }
        public decimal SubtotalIVA { get; set; }
        public decimal SubtotalIVA0 { get; set; }
        public decimal Subtotal { get; set; }
        public decimal PorcentajeDesc { get; set; }
        public decimal Descuento { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FactVenta FactVenta { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDetalle> DVDetalle { get; set; }
    }
}
