//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Sigla { get; set; }
        public bool SRI { get; set; }
        public string CodigoSRI { get; set; }
        public bool Electronico { get; set; }
        public bool Estado { get; set; }
    }
}
