//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int ID { get; set; }
        public int IDCiudad { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string TipoContribuyente { get; set; }
        public bool ObligContabilidad { get; set; }
        public bool ContEspecial { get; set; }
        public string NumResolucion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string RepresentNombre { get; set; }
        public string RepresentIdentificacion { get; set; }
        public string RepresentCelular { get; set; }
        public string RepresentEmail { get; set; }
        public string ContadorNombre { get; set; }
        public string ContadorIdentificacion { get; set; }
        public string ContadorCelular { get; set; }
        public string ContadorEmail { get; set; }
        public Nullable<System.Guid> IDGUID { get; set; }
        public byte[] Logo { get; set; }
        public bool EmisorFE { get; set; }
        public bool Estado { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
