//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaContabilidad
    {
        public int IDFV { get; set; }
        public long IDTC { get; set; }
        public string EstadoTransaccion { get; set; }
        public string InsUsuario { get; set; }
        public string InsPC { get; set; }
        public System.DateTime InsFecha { get; set; }
    }
}
