//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactCompra()
        {
            this.CtasPagar = new HashSet<CtasPagar>();
            this.DevCompra = new HashSet<DevCompra>();
            this.FCDetalle = new HashSet<FCDetalle>();
        }
    
        public int IDFC { get; set; }
        public int IDSU { get; set; }
        public Nullable<int> IDPT { get; set; }
        public int IDPV { get; set; }
        public int IDUS { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Autorizacion { get; set; }
        public string Numero { get; set; }
        public string FormaPago { get; set; }
        public decimal SubtotalIVA { get; set; }
        public decimal SubtotalIVA0 { get; set; }
        public decimal Subtotal { get; set; }
        public decimal PorcentajeDesc { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<decimal> SubtotalIVADesc { get; set; }
        public Nullable<decimal> SubtotalIVA0Desc { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtasPagar> CtasPagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevCompra> DevCompra { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCDetalle> FCDetalle { get; set; }
    }
}
