//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactVenta()
        {
            this.CtasCobrar = new HashSet<CtasCobrar>();
            this.DevVenta = new HashSet<DevVenta>();
            this.FVDetalle = new HashSet<FVDetalle>();
            this.RetencionV = new HashSet<RetencionV>();
            this.Tarjeta = new HashSet<Tarjeta>();
        }
    
        public int IDFV { get; set; }
        public Nullable<int> IDP { get; set; }
        public int IDCT { get; set; }
        public Nullable<int> IDIN { get; set; }
        public int IDSU { get; set; }
        public int IDPT { get; set; }
        public int IDUS { get; set; }
        public Nullable<int> IDEP { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Autorizacion { get; set; }
        public string Numero { get; set; }
        public string FormaPago { get; set; }
        public Nullable<decimal> PorcentajeComision { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public decimal SubtotalIVA { get; set; }
        public decimal SubtotalIVA0 { get; set; }
        public decimal Subtotal { get; set; }
        public decimal PorcentajeDesc { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<decimal> SubtotalIVADesc { get; set; }
        public Nullable<decimal> SubtotalIVA0Desc { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
        public decimal Efectivo { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<bool> Impreso { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtasCobrar> CtasCobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevVenta> DevVenta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FVDetalle> FVDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetencionV> RetencionV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjeta { get; set; }
        public virtual PuntoVenta PuntoVenta1 { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
