//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int IDKD { get; set; }
        public int IDUS { get; set; }
        public int IDSU { get; set; }
        public int IDPD { get; set; }
        public Nullable<int> IDMOT { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public decimal Stock { get; set; }
        public decimal Total { get; set; }
        public string Glosa { get; set; }
    
        public virtual MotivoMovInv MotivoMovInv { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
