//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBD
    {
        public int ID { get; set; }
        public string PC { get; set; }
        public string Usuario { get; set; }
        public string Aplicacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ErrorNum { get; set; }
        public int Linea { get; set; }
        public string Origen { get; set; }
        public string ErrorMsg { get; set; }
        public string Tipo { get; set; }
        public string Registro { get; set; }
    }
}
