//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovInvCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovInvCab()
        {
            this.MovInvDet = new HashSet<MovInvDet>();
        }
    
        public int IDMO { get; set; }
        public int IDUS { get; set; }
        public int IDSU { get; set; }
        public int IDMT { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Glosa { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public string PC { get; set; }
    
        public virtual MotivoMovInv MotivoMovInv { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovInvDet> MovInvDet { get; set; }
    }
}
