//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_response
    {
        public Nullable<int> request_id { get; set; }
        public string peer { get; set; }
        public string peer_db { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
    }
}
