//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPreparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenPreparacion()
        {
            this.OrdenPDetalle = new HashSet<OrdenPDetalle>();
        }
    
        public int ID { get; set; }
        public int IDSU { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string InsUsuario { get; set; }
        public string InsPC { get; set; }
        public Nullable<System.DateTime> InsFecha { get; set; }
        public string UpdUsuario { get; set; }
        public string UpdPC { get; set; }
        public Nullable<System.DateTime> UpdFecha { get; set; }
        public Nullable<bool> Impreso { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPDetalle> OrdenPDetalle { get; set; }
    }
}
