//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int IDPF { get; set; }
        public int IDOB { get; set; }
        public bool Ver { get; set; }
        public bool Buscar { get; set; }
        public bool Actualizar { get; set; }
        public bool Eliminar { get; set; }
        public bool Guardar { get; set; }
        public bool Imprimir { get; set; }
    
        public virtual Objetos Objetos { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
