//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCuentas
    {
        public int ID { get; set; }
        public int IDPCTA { get; set; }
        public int IDP { get; set; }
        public string NumeroCuenta { get; set; }
        public string Etiqueta { get; set; }
        public string Estado { get; set; }
    }
}
