//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanContable
    {
        public int ID { get; set; }
        public int IDPC { get; set; }
        public int IDEM { get; set; }
        public string Modelo { get; set; }
        public string Etiqueta { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    }
}
