//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.FVDetalle = new HashSet<FVDetalle>();
            this.Kardex = new HashSet<Kardex>();
            this.DCDetalle = new HashSet<DCDetalle>();
            this.DetDispensadorIslero = new HashSet<DetDispensadorIslero>();
            this.DTHDetalle = new HashSet<DTHDetalle>();
            this.DVDetalle = new HashSet<DVDetalle>();
            this.FCDetalle = new HashSet<FCDetalle>();
            this.Ingredientes = new HashSet<Ingredientes>();
            this.Ingredientes1 = new HashSet<Ingredientes>();
            this.Inventario = new HashSet<Inventario>();
            this.MovInvDet = new HashSet<MovInvDet>();
            this.OrdenPDetalle = new HashSet<OrdenPDetalle>();
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
            this.ProductoImagen = new HashSet<ProductoImagen>();
            this.ProductoInfoAdicional = new HashSet<ProductoInfoAdicional>();
            this.ProductoUnidad = new HashSet<ProductoUnidad>();
            this.ProformaVtaDet = new HashSet<ProformaVtaDet>();
            this.THDetalle = new HashSet<THDetalle>();
        }
    
        public int IDPD { get; set; }
        public Nullable<int> IDFB { get; set; }
        public Nullable<int> IDCT { get; set; }
        public Nullable<int> IDGP { get; set; }
        public Nullable<int> IDSG { get; set; }
        public Nullable<int> IDPRE { get; set; }
        public Nullable<int> IDMarca { get; set; }
        public Nullable<int> IDUnidad { get; set; }
        public Nullable<int> IDDeducible { get; set; }
        public Nullable<int> IDIVA { get; set; }
        public Nullable<int> IDIRBP { get; set; }
        public Nullable<int> IDICE { get; set; }
        public Nullable<int> IDRetencionIVA { get; set; }
        public Nullable<int> IDRetencionIR { get; set; }
        public string Codigo { get; set; }
        public string CodigoExterno { get; set; }
        public string Nombre { get; set; }
        public decimal Costo { get; set; }
        public decimal PVP { get; set; }
        public decimal PVM { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Subsidio { get; set; }
        public decimal Comision { get; set; }
        public decimal PCP { get; set; }
        public Nullable<int> Tipo { get; set; }
        public bool IVA { get; set; }
        public Nullable<bool> IRBP { get; set; }
        public Nullable<bool> ICE { get; set; }
        public Nullable<bool> Serie { get; set; }
        public Nullable<bool> Combo { get; set; }
        public Nullable<int> Clasificacion { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Fabricante Fabricante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FVDetalle> FVDetalle { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual ImpuestoRetencion ImpuestoRetencion { get; set; }
        public virtual ImpuestoRetencion ImpuestoRetencion1 { get; set; }
        public virtual ImpuestoTarifa ImpuestoTarifa { get; set; }
        public virtual ImpuestoTarifa ImpuestoTarifa1 { get; set; }
        public virtual ImpuestoTarifa ImpuestoTarifa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCDetalle> DCDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetDispensadorIslero> DetDispensadorIslero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTHDetalle> DTHDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDetalle> DVDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCDetalle> FCDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredientes> Ingredientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovInvDet> MovInvDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPDetalle> OrdenPDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
        public virtual SubGrupo SubGrupo { get; set; }
        public virtual TipoDeducible TipoDeducible { get; set; }
        public virtual Unidad Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoImagen> ProductoImagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoInfoAdicional> ProductoInfoAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoUnidad> ProductoUnidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaVtaDet> ProformaVtaDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THDetalle> THDetalle { get; set; }
    }
}
