//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.DevCompra = new HashSet<DevCompra>();
            this.FactCompra = new HashSet<FactCompra>();
            this.ProveedorEmail = new HashSet<ProveedorEmail>();
            this.ProveedorInfoAdicional = new HashSet<ProveedorInfoAdicional>();
        }
    
        public int IDPV { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<int> IDCiudad { get; set; }
        public Nullable<int> IDTipoIdentificacion { get; set; }
        public string CEDRUC { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public Nullable<bool> SujetoRetencion { get; set; }
        public string TipoContribuyente { get; set; }
        public string TipoEntidad { get; set; }
        public string TipoEmisor { get; set; }
        public string AutorizacionSRI { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevCompra> DevCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCompra> FactCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorEmail> ProveedorEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorInfoAdicional> ProveedorInfoAdicional { get; set; }
    }
}
