//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetencionCDet
    {
        public int IDR { get; set; }
        public decimal BaseImponible { get; set; }
        public int IDIMP { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual ImpuestoRetencion ImpuestoRetencion { get; set; }
        public virtual RetencionC RetencionC { get; set; }
    }
}
