//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetencionC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetencionC()
        {
            this.RetencionCDet = new HashSet<RetencionCDet>();
        }
    
        public int IDR { get; set; }
        public int IDUS { get; set; }
        public int IDSU { get; set; }
        public int IDPT { get; set; }
        public int IDF { get; set; }
        public string NumeroRetencion { get; set; }
        public string EjercicioFiscal { get; set; }
        public bool Estado { get; set; }
        public bool Asumida { get; set; }
        public string Concepto { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string UsuarioUpd { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public decimal ValorRetencion { get; set; }
        public Nullable<decimal> ValorRetencionIva { get; set; }
        public Nullable<decimal> ValorRetencionRenta { get; set; }
    
        public virtual FactCompra FactCompra { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetencionCDet> RetencionCDet { get; set; }
    }
}
