//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPagos
    {
        public int IDEP { get; set; }
        public string CARGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public short ANO { get; set; }
        public byte MESNUM { get; set; }
        public string MES { get; set; }
        public decimal SUELDO { get; set; }
        public decimal INGRESOS { get; set; }
        public decimal COMISIONES { get; set; }
        public decimal DESCUENTOS { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
