//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysarticleupdates
    {
        public int artid { get; set; }
        public int pubid { get; set; }
        public int sync_ins_proc { get; set; }
        public int sync_upd_proc { get; set; }
        public int sync_del_proc { get; set; }
        public bool autogen { get; set; }
        public int sync_upd_trig { get; set; }
        public Nullable<int> conflict_tableid { get; set; }
        public Nullable<int> ins_conflict_proc { get; set; }
        public bool identity_support { get; set; }
    }
}
