//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssubscriptions
    {
        public int artid { get; set; }
        public short srvid { get; set; }
        public string dest_db { get; set; }
        public byte status { get; set; }
        public byte sync_type { get; set; }
        public string login_name { get; set; }
        public int subscription_type { get; set; }
        public byte[] distribution_jobid { get; set; }
        public byte[] timestamp { get; set; }
        public byte update_mode { get; set; }
        public bool loopback_detection { get; set; }
        public bool queued_reinit { get; set; }
        public byte nosync_type { get; set; }
        public string srvname { get; set; }
    }
}
