//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysschemaarticles
    {
        public int artid { get; set; }
        public string creation_script { get; set; }
        public string description { get; set; }
        public string dest_object { get; set; }
        public string name { get; set; }
        public int objid { get; set; }
        public int pubid { get; set; }
        public byte pre_creation_cmd { get; set; }
        public int status { get; set; }
        public byte type { get; set; }
        public byte[] schema_option { get; set; }
        public string dest_owner { get; set; }
    }
}
