//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioDespacho
    {
        public int ID { get; set; }
        public int IDUSUARIO { get; set; }
        public Nullable<decimal> Cupo { get; set; }
        public string Estacion { get; set; }
        public string Usuario { get; set; }
        public string Estado { get; set; }
    }
}
