//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAperturaCajaDet
    {
        public int DESGIDAPERTURA { get; set; }
        public int DESGDENID { get; set; }
        public string DESGDENNOMBRE { get; set; }
        public decimal DESGDENVALOR { get; set; }
        public int DESGCANTIDAD { get; set; }
        public decimal DESGTOTAL { get; set; }
        public string DESGTIPO { get; set; }
        public string DESGTIPODESC { get; set; }
    }
}
