//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCierreCaja
    {
        public int ITEMIDAPERTURA { get; set; }
        public short ITEMLINEA { get; set; }
        public string ITEMCATCODIGO { get; set; }
        public string ITEMCATNOMBRE { get; set; }
        public decimal ITEMMONTO { get; set; }
    }
}
