//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClienteCtas
    {
        public int IDCTA { get; set; }
        public int IDCT { get; set; }
        public string CEDRUC { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public decimal Cupo { get; set; }
        public decimal ValorCta { get; set; }
        public string DetalleCta { get; set; }
        public int IDDCTA { get; set; }
        public string Tipo { get; set; }
        public string Concepto { get; set; }
        public decimal Bono { get; set; }
        public decimal ValorCtaDet { get; set; }
        public decimal Saldo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string DetalleCtaDet { get; set; }
    }
}
