//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClienteFull
    {
        public int ID { get; set; }
        public string IDENTIFICACION { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELFCONVENCIONAL { get; set; }
        public string TELEFCELULAR { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> SUJETORETENCION { get; set; }
        public string TIPOCONTRIBUYENTECOD { get; set; }
        public string TIPOCONTRIBUYENTE { get; set; }
        public string TIPOENTIDADCOD { get; set; }
        public string TIPOENDITAD { get; set; }
        public string TIPOCLIENTECOD { get; set; }
        public string TIPOCLIENTE { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public int TIDENTID { get; set; }
        public string TIDENTCODSRI { get; set; }
        public string TIDENTDESCRIPCION { get; set; }
        public bool TIDENTESTADO { get; set; }
        public Nullable<int> CATEGID { get; set; }
        public string CATEGDESCRIPCION { get; set; }
        public Nullable<bool> CATEGESTADO { get; set; }
        public Nullable<int> CIUDADID { get; set; }
        public string CIUDADCODIGO { get; set; }
        public string CIUDADDESCRIPCION { get; set; }
        public Nullable<bool> CIUDADESTADO { get; set; }
        public Nullable<int> PAISID { get; set; }
        public string PAISCODIGO { get; set; }
        public string PAISDESCRIPCION { get; set; }
        public Nullable<bool> PAISESTADO { get; set; }
        public Nullable<int> REGIONID { get; set; }
        public string REGIONDESCRIPCION { get; set; }
        public Nullable<bool> REGIONESTADO { get; set; }
        public Nullable<int> CONTINENTEID { get; set; }
        public string CONTINENTEDESCRIPCION { get; set; }
        public Nullable<bool> CONTINENTEESTADO { get; set; }
        public Nullable<int> EMAILID { get; set; }
        public string EMAILDESCRIPCION { get; set; }
        public Nullable<bool> EMAILINFOCOMPROBANTE { get; set; }
        public Nullable<bool> EMAILESTADO { get; set; }
        public Nullable<int> INFOID { get; set; }
        public Nullable<short> INFOORDEN { get; set; }
        public string INFOCAMPO { get; set; }
        public string INFOCONTENIDO { get; set; }
        public Nullable<bool> INFOESTADO { get; set; }
    }
}
