//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCobros
    {
        public int IDCC { get; set; }
        public System.DateTime FECHAREG { get; set; }
        public string TIPOCUOTA { get; set; }
        public string FORMAPAGO { get; set; }
        public decimal MONTO { get; set; }
        public decimal SALDODOC { get; set; }
        public decimal PORCCOMISION { get; set; }
        public decimal MONTOCOMISION { get; set; }
        public bool ESTADO { get; set; }
        public int DOCID { get; set; }
        public System.DateTime DOCFECHA { get; set; }
        public string DOCTIPO { get; set; }
        public string DOCNUMERO { get; set; }
        public decimal DOCTOTAL { get; set; }
        public decimal DOCSALDO { get; set; }
        public int CLTEID { get; set; }
        public string CLTEIDENTIFICACION { get; set; }
        public string CLTENOMBRE { get; set; }
        public string CLTECATEGORIA { get; set; }
        public int USUID { get; set; }
        public string USUNOMBRE { get; set; }
        public string USULOGIN { get; set; }
        public int PTOVTAID { get; set; }
        public string PTOVTANOMBRE { get; set; }
        public int SUCID { get; set; }
        public string SUCNOMBRE { get; set; }
    }
}
