//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCompraCabFull
    {
        public int DOCID { get; set; }
        public System.DateTime DOCFECHAREG { get; set; }
        public string DOCTIPO { get; set; }
        public string DOCAUTORIZACION { get; set; }
        public string DOCNUMERO { get; set; }
        public string DOCFORMAPAGO { get; set; }
        public decimal DOCSUBTOTALIVA { get; set; }
        public decimal DOCSUBTOTAL0 { get; set; }
        public decimal DOCSUBTOTAL { get; set; }
        public decimal DOCDESCPORC { get; set; }
        public decimal DOCDESCUENTO { get; set; }
        public Nullable<decimal> DOCSUBTOTALIVADESC { get; set; }
        public Nullable<decimal> DOCSUBTOTALIVA0DESC { get; set; }
        public decimal DOCIVA { get; set; }
        public decimal DOCTOTAL { get; set; }
        public decimal DOCSALDO { get; set; }
        public string DOCESTADO { get; set; }
        public int PROVID { get; set; }
        public string PROVIDENTIFICACION { get; set; }
        public string PROVNOMBRE { get; set; }
        public string PROVDIRECCION { get; set; }
        public string PROVTELEFONO { get; set; }
        public int USUID { get; set; }
        public string USUNOMBRE { get; set; }
        public string USULOGIN { get; set; }
        public int PTOVTAID { get; set; }
        public string PTOVTANOMBRE { get; set; }
        public string PTOVTASERIE1 { get; set; }
        public string PTOVTASERIE2 { get; set; }
        public int SUCID { get; set; }
        public string SUCNOMBRE { get; set; }
        public int SUCCIUDADID { get; set; }
        public string SUCCIUDADNOMBRE { get; set; }
    }
}
