//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDistGeografica
    {
        public int CIUDADID { get; set; }
        public string CIUDADCODIGO { get; set; }
        public string CIUDADDESCRIPCION { get; set; }
        public Nullable<bool> CIUDADESTADO { get; set; }
        public int PAISID { get; set; }
        public string PAISCODIGO { get; set; }
        public string PAISDESCRIPCION { get; set; }
        public bool PAISESTADO { get; set; }
        public int REGIONID { get; set; }
        public string REGIONDESCRIPCION { get; set; }
        public bool REGIONESTADO { get; set; }
        public int CONTINENTEID { get; set; }
        public string CONTINENTEDESCRIPCION { get; set; }
        public bool CONTINENTEESTADO { get; set; }
    }
}
