//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.TarjetaHabiente = new HashSet<TarjetaHabiente>();
            this.ClienteFlota = new HashSet<ClienteFlota>();
        }
    
        public int ID { get; set; }
        public int IDClase { get; set; }
        public int IDModelo { get; set; }
        public int IDMarca { get; set; }
        public int IDColor1 { get; set; }
        public int IDColor2 { get; set; }
        public string Placa { get; set; }
        public string Estado { get; set; }
        public string InsUsuario { get; set; }
        public string InsPC { get; set; }
        public System.DateTime InsFecha { get; set; }
        public string UpdUsuario { get; set; }
        public string UpdPC { get; set; }
        public Nullable<System.DateTime> UpdFecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetaHabiente> TarjetaHabiente { get; set; }
        public virtual Clase Clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteFlota> ClienteFlota { get; set; }
        public virtual Color Color { get; set; }
        public virtual Color Color1 { get; set; }
        public virtual Marca1 Marca1 { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
