//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFlujoCaja
    {
        public int MOVID { get; set; }
        public System.DateTime MOVFECHAREG { get; set; }
        public string MOVTIPO { get; set; }
        public string MOVENTIDAD { get; set; }
        public decimal MOVVALOR { get; set; }
        public string MOVGLOSA { get; set; }
        public int RUBID { get; set; }
        public string RUBNOMBRE { get; set; }
        public int USUID { get; set; }
        public string USUNOMBRE { get; set; }
        public string USULOGIN { get; set; }
        public int PTOVTAID { get; set; }
        public string PTOVTANOMBRE { get; set; }
        public int SUCID { get; set; }
        public string SUCNOMBRE { get; set; }
    }
}
