//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMinAndMax
    {
        public int IDSU { get; set; }
        public int IDPD { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Tipo { get; set; }
        public decimal MaxP { get; set; }
        public decimal MinP { get; set; }
        public decimal Stock { get; set; }
    }
}
