//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPagos
    {
        public int IDCP { get; set; }
        public System.DateTime FECHAREG { get; set; }
        public string FormaPago { get; set; }
        public decimal MONTO { get; set; }
        public decimal SALDODOC { get; set; }
        public bool Estado { get; set; }
        public int DOCID { get; set; }
        public System.DateTime DOCFECHAREG { get; set; }
        public string DOCTIPO { get; set; }
        public string DOCNUMERO { get; set; }
        public decimal DOCTOTAL { get; set; }
        public decimal DOCSALDO { get; set; }
        public int PROVID { get; set; }
        public string PROVIDENTIFICACION { get; set; }
        public string PROVNOMBRE { get; set; }
        public int USUID { get; set; }
        public string USUNOMBRE { get; set; }
        public string USULOGIN { get; set; }
        public int PTOVTAID { get; set; }
        public string PTOVTANOMBRE { get; set; }
        public int SUCID { get; set; }
        public string SUCNOMBRE { get; set; }
    }
}
