//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProformaVtaCab
    {
        public int PROFID { get; set; }
        public System.DateTime PROFFECHA { get; set; }
        public string PROFFORMAPAGOABREV { get; set; }
        public string PROFFORMAPAGO { get; set; }
        public string PROFNUMERO { get; set; }
        public int PROFSECUENCIAL { get; set; }
        public decimal PROFSUBTOTALIVA { get; set; }
        public decimal PROFSUBTOTALIVA0 { get; set; }
        public decimal PROFSUBTOTAL { get; set; }
        public decimal PROFPORCDESCUENTO { get; set; }
        public decimal PROFVALORDESCUENTO { get; set; }
        public decimal PROFSUBTOTALIVADESC { get; set; }
        public decimal PROFSUBTOTALIVA0DESC { get; set; }
        public decimal PROFIVA { get; set; }
        public decimal PROFTOTAL { get; set; }
        public string PROFESTADOABREV { get; set; }
        public string PROFESTADO { get; set; }
        public int CLTEID { get; set; }
        public string CLTEIDENTIFICACION { get; set; }
        public string CLTENOMBRE { get; set; }
        public string CLTEDIRECCION { get; set; }
        public string CLTETELEFONO { get; set; }
        public string CLTETIPO { get; set; }
        public string CLTECATEGORIA { get; set; }
        public int SUCID { get; set; }
        public string SUCNOMBRE { get; set; }
        public string SUCDIRECCION { get; set; }
        public string SUCADMINISTRADOR { get; set; }
        public string SUCTELEFONO { get; set; }
        public int PTOVTAID { get; set; }
        public string PTOVTANOMBRE { get; set; }
        public int USUID { get; set; }
        public string USULOGIN { get; set; }
        public string USUNOMBRE { get; set; }
    }
}
