//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegistroCobrosFacturas
    {
        public int IDCC { get; set; }
        public int IDSU { get; set; }
        public int IDFV { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TIPO { get; set; }
        public string FormaPago { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public decimal PorcentajeComision { get; set; }
        public decimal Comision { get; set; }
        public bool Estado { get; set; }
        public int IDEP { get; set; }
        public string RECAUDADOR { get; set; }
    }
}
