//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRetencionDE
    {
        public int IDR { get; set; }
        public Nullable<long> IDDD { get; set; }
        public string NumeroRetencion { get; set; }
        public string Concepto { get; set; }
        public decimal ValorRetencion { get; set; }
        public System.DateTime RETFECHA { get; set; }
        public bool Asumida { get; set; }
        public int IDF { get; set; }
        public Nullable<int> IDSU { get; set; }
        public Nullable<int> IDPT { get; set; }
        public Nullable<System.DateTime> FACTFECHA { get; set; }
        public string FECHATIPO { get; set; }
        public string FACTAUTORIZACION { get; set; }
        public string FACTNUMERO { get; set; }
        public string FACTFORMAPAGO { get; set; }
        public Nullable<decimal> FACTTOTAL { get; set; }
        public string FACTESTADO { get; set; }
        public string EstadoDocumento { get; set; }
        public Nullable<int> IDPV { get; set; }
        public string CEDRUC { get; set; }
        public string PROVEEDOR { get; set; }
        public string CATPROVEEDOR { get; set; }
    }
}
