//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRolPagosIndividual
    {
        public int IDEP { get; set; }
        public string EMPLEADO { get; set; }
        public string EMPCEDULA { get; set; }
        public string EMPTELEFONO { get; set; }
        public string EMPCELULAR { get; set; }
        public string EMPDIRECCION { get; set; }
        public decimal EMPSUELDO { get; set; }
        public bool EMPESTADO { get; set; }
        public string CARGO { get; set; }
        public string TIPO { get; set; }
        public string TIPORUBRO { get; set; }
        public string RUBRO { get; set; }
        public decimal VALOR { get; set; }
        public decimal VALORINGRESOS { get; set; }
        public decimal VALORDESCUENTOS { get; set; }
        public string RUBROINGRESOS { get; set; }
        public string RUBRODESCUENTOS { get; set; }
        public short ANO { get; set; }
        public byte MESNUM { get; set; }
        public string MES { get; set; }
    }
}
