//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransaccion
    {
        public string PERIODO { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MESNUMERO { get; set; }
        public string MES { get; set; }
        public string TIPOMIVIMIENTO { get; set; }
        public string TIPOTRANSACCION { get; set; }
        public int ESTABLECIMIENTOID { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public Nullable<int> PUNTOEMISIONID { get; set; }
        public string PUNTOEMISION { get; set; }
        public int USUARIOID { get; set; }
        public string USUARIO { get; set; }
        public string USUARIONOMBRE { get; set; }
        public int ENTIDADID { get; set; }
        public string ENTIDADIDENTIFICACION { get; set; }
        public string ENTIDADNOMBRE { get; set; }
        public string ENTIDADCATEGORIA { get; set; }
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DOCUMENTOTIPO { get; set; }
        public string DOCUMENTOAUTORIZACION { get; set; }
        public string DOCUMENTONUMERO { get; set; }
        public string FORMAPAGO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> VALORINGRESO { get; set; }
        public Nullable<decimal> VALOREGRESO { get; set; }
        public string ESTADO { get; set; }
    }
}
