//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVentaFFE
    {
        public int IDFV { get; set; }
        public Nullable<long> IDDD { get; set; }
        public int IDSU { get; set; }
        public int IDPT { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TIPO { get; set; }
        public string Autorizacion { get; set; }
        public string Numero { get; set; }
        public string FORMAPAGO { get; set; }
        public decimal Total { get; set; }
        public string ESTADO { get; set; }
        public string EstadoDocumento { get; set; }
        public Nullable<int> IDIN { get; set; }
        public int IDCT { get; set; }
        public string CEDRUC { get; set; }
        public string CLIENTE { get; set; }
        public string CATCLIENTE { get; set; }
        public Nullable<decimal> ValorRetencion { get; set; }
    }
}
