//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Aldebaran_CobrosPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVentaFContabilidad
    {
        public int IDFV { get; set; }
        public Nullable<long> IDTC { get; set; }
        public System.DateTime Fecha { get; set; }
        public string TIPO { get; set; }
        public string FORMAPAGO { get; set; }
        public string ESTADO { get; set; }
        public string EstadoTransaccion { get; set; }
    }
}
